### PR TITLE
Master fb support

### PR DESCRIPTION
**Pull request by therealjumbo**
@bitbank2 are you open to these modifications? I have a few more to make yet, this isn't ready, but I wanted to make sure you were ok with this direction.

### CODE REVIEW

**Comment by bitbank2** [comment]
I'm wondering if it would be better to start with my AnimatedGIF library instead of modifying this one. The new library has a better design and is more modular for controlling where the output goes.

**Comment by therealjumbo** [comment]
Our screen is 800x480.

**Comment by bitbank2** [comment]
The new lib has no size limits, it just emits one line at a time as output. I set an arbitrary max width of 320 to reduce RAM usage on Arduino, but you can just change that #define.

**Comment by therealjumbo** [comment]
In your testing did you find the other one to be faster?

**Comment by bitbank2** [comment]
The new library is slightly faster than the old; I did find a couple of additional optimizations.

**Comment by therealjumbo** [comment]
A few thoughts:
* I prefer c to c++ mainly because I know c better and feel more confident in my ability to debug it.
* I'm gonna test with this first, and if it's fast enough, then I guess the extra speed from the other library is not really a big deal. I'm only displaying a GIF as a splash screen on bootup, so the performance isn't really a big deal as long as the animation plays at the correct FPS. Right now I'm using dfbplay which seems to lag behind the correct FPS by more than 25% on my board and screen.
* This repo already has the executable written, the other one is a library and I'd need to hack up one of your examples into an executable for linux (I don't want my users to have to recompile the app in order to change the image, so the example linux app wouldn't work because it uses the GIFs in the *.h format.) 
* It'd be really cool to send a patch to buildroot upstream so buildroot users can easily build your GIF player, but they generally want to avoid patching upstream if they can help it. Your other repo would need either that define patched, or Makefile work to plumb in a way to choose a number (and a default) in addition to another linux example app and the Makefile etc for that.

**Comment by therealjumbo** [comment]
Overall, thanks so much for your work, it looks really cool :)

**Comment by bitbank2** [comment]
The new GIF library is actually C code with a C++ "wrapper" exposed to be an Arduino library. It's quite easy to lift the code out, but perhaps I should split the C code out into its own file and include it in the C++ code.

**Comment by therealjumbo** [comment]
Should this support 89a or only 87a GIFs? With my GIF the entire image is skewing to the left.

**Comment by bitbank2** [comment]
It should support both. Skewing of the image shouldn't be related to the GIF version. Is it < 8-bpp? Can you send me a sample image to test?

**Comment by therealjumbo** [comment]
Sure, https://drive.google.com/file/d/14ZZVSusTrWmIQxi_opC1qxj8oIcAiCDk/view?usp=sharing

**Comment by therealjumbo** [comment]
I also saw you adding a simple linux c only app to the other repo [here](https://github.com/bitbank2/AnimatedGIF/pull/9) but I don't see the file gif.c anywhere in the repo?

**Comment by bitbank2** [comment]
Thanks for catching that. I started to implement it and then stopped mid-way. I pushed gif.c. I still need to merge it with the master branch. What are you displaying that GIF on? I don't have a convenient display for testing. Is this for RPI 1080p?

**Comment by therealjumbo** [comment]
Were you able to reproduce the issue with that gif on with this repo? I built my branch in Ubuntu 18.04, switched to tty7, and ran `./gp --in thatfile.gif` and had the issue. 

I'll check out your branch on the other repo, port this linux app over to it (I need to select which fb to write to, and I need to read regular files not ones compiled in, and maybe something else I'm forgetting), and see if that works any better. Not sure when I'll get around to it.

**Comment by therealjumbo** [comment]
I missed part of your comment. No it's custom embedded hardware, but like I said in my other comment, I was able to reproduce on Ubuntu 18.04 by compiling it there and then escaping X by switching to a tty with ctrl-alt-f6 and then playing it. Something similar should work on almost any linux distro.

**Comment by therealjumbo** [comment]
I wound up getting my GIF to play nice at the right speed with mpv. However if you want me to help you diagnose this issue, I'd be happy to. I really think your projects are cool with your focus on speed and no dependencies. Lemme know.

**Comment by bitbank2** [comment]
I tested your GIF on my AnimatedGIF library and it works perfectly. There may be an issue in gif_play, but I've focused my energy on AnimatedGIF now, so unfortunately I'm not going to be maintaining gif_play.

**Comment by therealjumbo** [comment]
Fair enough, I wouldn't want to maintain two versions of largely the same thing. :) Maybe I'll get some time to port the linux app in this repo into the other repo. I do see that on the linux branch with gif.c the Gifdraw callback is empty?

**Comment by bitbank2** [comment]
I wrote a perf test with an empty GIFDRAW callback, but otherwise you need to pick up the pixels there.

**Pull request closed without merging**
